name: Update repository submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    name: Update submodules and create PR if needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      ## Execute submodules update script
      - name: Run update submodules script
        run: |
          chmod +x ./scripts/update-submodules.sh
          ./scripts/update-submodules.sh

      ## Check for updated modules
      - name: Check for changes in ./modules
        id: changes
        run: |
          git add ./modules
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Configure git to use GitHub token for HTTPS
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      ## Commit changes if 1 or more modules updated
      - name: Commit and create PR if there are changes
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(submodules): Update submodules"
          branch: fix/update-submodules
          title: "chore(submodules): Update submodules"
          body: "Pulled changes for each git submodule"
          add-paths: ./modules
