name: Update repository submodules

on:
  ## Manual trigger
  # workflow_dispatch:
  ## Scheduled trigger
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  update-submodules:
    name: Update submodules and create PR if needed
    runs-on: ubuntu-latest
    steps:
      ## Use READ-ONLY token for checkout and submodules
      - uses: actions/checkout@v4
        with:
          submodules: false
          token: ${{ secrets.GH_READONLY_PAT }}

      - name: Rewrite submodule URLs to include READ-ONLY PAT and update submodules
        env:
          GH_READONLY_PAT: ${{ secrets.GH_READONLY_PAT }}
        run: |
          git config --global url."https://${GH_READONLY_PAT}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git submodule sync
          git submodule update --init --recursive

      ## Run submodules update script
      - name: Run update submodules script
        run: |
          chmod +x ./scripts/update-submodules.sh
          ./scripts/update-submodules.sh

      ## Check for updated modules
      - name: Check for changes in ./modules
        id: changes
        run: |
          git add ./modules
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      ## Commit and create PR if there are changes, using READ-WRITE token
      - name: Commit and create PR if there are changes
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_READWRITE_PAT }}
          commit-message: "chore(submodules): Update submodules"
          branch: chore/update-submodules
          base: main
          title: "chore(submodules): Update submodules"
          body: "Pulled changes for each git submodule"
          add-paths: ./modules
