name: Update repository submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    name: Update submodules and create PR if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          ## Cache last uv install
          enable-cache: true
          ## Or pin a specific version
          # version: "0.7.13"

      ## Execute submodules update script
      - name: Run update script
        run: uv run scripts/update_project.py

      ## Check for updated modules
      - name: Check for changes in ./modules
        id: changes
        run: |
          git add ./modules
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      ## Commit changes if 1 or more modules updated
      - name: Commit and create PR if there are changes
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(submodules): Update submodules"
          branch: fix/update-submodules
          title: "chore(submodules): Update submodules"
          body: "Pulled changes for each git submodule"
          add-paths: ./modules
